version: "3.8"
services:
  database:
    image: mysql:8.1.0
    ports:
      - 8081:8081
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_USER: root
      MYSQL_DB: vaccination_management
  backend:
    image: nqanvo/backend-vm:1
    ports:
      - 8080:8080
    build:
      context: ./
    depends_on:
      - database
